var f = [];				
f[0]	= "v0.0.9";			
f[1]	= "01 Cinnamon Girl.mp3";		
f[2]	= "02 Everybody Knows This Is Nowhere.mp3";		
f[3]	= "03 Round & Round (It Won't Be Long).mp3";		
f[4]	= "04 Down by the River.mp3";		
f[5]	= "05 The Losing End (When You're On).mp3";		
f[6]	= "06 Running Dry (Requiem for the Rockets).mp3";		
f[7]	= "07 Cowgirl in the Sand.mp3";		
